language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: process.env.API_KEY
    secure: gxeqemOvorJL4n1utPSHekeEUIvN12riZiZ4jQfBGY5+dHgNMFlP+80cCUD4E1RxdEY5rYpwTU/UU4PK9dD7edNRmsP8u8So0/Aco/RK8DFdn5jh3XwOjvLlaNS2326ZCRmrNvYq5kpbPDn4S7RMX8SFpCURCA+OBDgYYXmI22lLGup66LOBpWn6sb3L7FODNr2YTa81/RYZ4mkB09DGjyO2qo3W4JJWdDwdosRx4r8ApLmHfxukwTbOllURC3kplY4bjttsDZtE0WTh7xeaWowgngiHIaIUuz6xI6uZYPm0jfZiAt6QzDX8Gd8SIemAu2dYifwVcCUNKCECxZtxeLubCg9tdH683jFXssiHqkuk7yirKc4G+QF972KK/zz/NCOW1rTAocOilDtB88KEp+HY2T/hhbwxPC5t1vdm+e4goZqvKoZ/DWmW/oNMEz2fBZGYqTlUl8YCGQsBchTD8eJ1ZpT05vXa3PO441j+15jmVggMz5eJ7Uk6mBl450SKulrnr40q799E9E06AE4PO+zcazdjjJfXkDySrfKA+gXxxNoIis0WSPGD5JrCHYzGRCeSEJEfaE+7e5e2g9elLi3r7AcKsJTRIX5AwUMGBmDtq42mjUyXR2Fs92qANnG7J5rF8OB5qAQOuFzYMXKvdvY+LnP7fIYcYwmhBg7+n78=
  app: obscure-bayou-58711
  on:
    repo: soundofsilence75/node-shopping-list-integration-tests
